var LangTexts = {
	en: {
		'userID':'user-id',
		'QuickPlay':'Quick Play',
		'Ranked':'Competitive',
		'ActualRanking':'Actual Ranking',
		'Victories':'Victories',
		'TimePlayed':'Time Played',
		'Medals':'Medals',
		'GeneralData':'General Data',
		'Heroes':'Heroes',
		'BestGameResults':'Best Game Results',
		'AllDataHeroe':'All Heroes Data',
		'WinedGames':'Games Win',
		'Elims.Proportion':'Kills/Deaths',
		'Accuracy':'Accuracy',
		'BestMultikill':'Best Multikill',
		'BestKillStrike':'Best Killstrike',
		'Max.HeroeDamage':'Max. Heroe Damage',
		'TotalEliminations':'Total Eliminations',
		'TotalDeaths':'Total Deaths',
		'FinalBlows':'Final Blows',
		'Eliminations':'Eliminations',
		'HeroeDamage':'Heroe Damage',
		'ObjectiveTime':'Objective Time',
		'Deaths':'Deaths',
		'BarrierDamage':'Barrier Damage',
		'Object.Kills':'Objective Kills',
		'SoloElims.':'Solo Eliminations',
		'OnFireTime':'On Fire Time',
		'Healing':'Healing',
		'Off.Asists':'Off. Assists',
		'EnviromentKills':'Enviroment Kills',
		'KillStrike':'KillStrike',
		'DefensiveAssists':'Def. Assists'
	},
	es: {
		'userID':'usuario-id',
		'QuickPlay':'Partida Rápida',
		'Ranked':'Competitivo',
		'ActualRanking':'Ranking Actual',
		'Victories':'Victorias',
		'TimePlayed':'Tiempo Jugado',
		'Medals':'Medallas',
		'GeneralData':'Datos totales',
		'Heroes':'Héroes',
		'BestGameResults':'Mejor dato por partida',
		'AllDataHeroe':'Todos los datos de los héroes',
		'WinedGames':'Partidas Ganadas',
		'Elims.Proportion':'Proporción Elims.',
		'Accuracy':'Precisión',
		'BestMultikill':'Mayor Baja Múltiple',
		'BestKillStrike':'Mayor racha de bajas',
		'Max.HeroeDamage':'Max. daño a Héroes',
		'TotalEliminations':'Eliminaciones Totales',
		'TotalDeaths':'Muertes Totales',
		'FinalBlows':'Golpes de Gracia',
		'Eliminations':'Eliminaciones',
		'HeroeDamage':'Daño a Héroes',
		'ObjectiveTime':'Tiempo en Objetivos',
		'Deaths':'Muertes',
		'BarrierDamage':'Daño a Barreras',
		'Object.Kills':'Elims. Objetivos',
		'SoloElims.':'Elims. en solitario',
		'OnFireTime':'Tiempo On Fire',
		'Healing':'Sanación',
		'Off.Asists':'Asistencias Of.',
		'EnviromentKills':'Elims. Entorno',
		'KillStrike':'Racha de Elims.',
		'DefensiveAssists':'Asistencias Def.'
	},
	fr: {
		'userID':'utilisateur-id',
		'QuickPlay':'jeu rapide',
		'Ranked':'compétitif',
		'ActualRanking':'classement actuel',
		'Victories':'Victories',
		'TimePlayed':'Temps joué',
		'Medals':'Médailles',
		'GeneralData':'Total des données',
		'Heroes':'Héros',
		'BestGameResults':'Meilleurs résultats par jeu',
		'AllDataHeroe':'Toutes les données des héros',
		'WinedGames':'victoires',
		'Elims.Proportion':'tue/mort',
		'Accuracy':'précision',
		'BestMultikill':'meilleur multikill',
		'BestKillStrike':'meilleur Killstrike',
		'Max.HeroeDamage':'dommages héros maximal',
		'TotalEliminations':'Total des éliminations',
		'TotalDeaths':'Total de décès',
		'FinalBlows':'Final Blows',
		'Eliminations':'éliminations',
		'HeroeDamage':'Heroe Damage',
		'ObjectiveTime':'temps objectif',
		'Deaths':'décès',
		'BarrierDamage':'dégâts de la barrière',
		'Object.Kills':'Tue sur l\'objectif',
		'SoloElims.':'éliminations en solo',
		'OnFireTime':'en temps de feu',
		'Healing':'guérison',
		'Off.Asists':'aides à l\'offensive',
		'EnviromentKills':'tue l\'environnement',
		'KillStrike':'tuer grève',
		'DefensiveAssists':'aides défensives'
	},
}